### ISSUE TITLE
Dependencies [minor issue]

### ISSUE THREAD

**Issue by adRn-s** [EcoJulia/Microbiome.jl#110]
I have run all the docs without any trouble, except for the need to manually install `Dictionaries` in order to use its classes and methods. Thankfully, the clear narration and explicit mention of this dependency helped a lot. So it is nothing that the users would be unaware. But for the sake of simplicity, I am opening the issue so that it can be addressed.

Leaving the installation issues aside, there's no mention in the docs about loading the libraries: `Microbiome`, `Dictionaries`, or `SparseArrays`. I understand the first one is obvious, but the other two shouldn't be autoloaded with the first one? I had to add the import lines of code here and there when the functions through an error while following the docs.

**Comment by kescobo** [comment]
Can you point me to the part of the docs you're referring to? I searched the docs for "sparse" and "spzeros" and only found [this spot](https://docs.ecojulia.org/Microbiome.jl/latest/profiles/#Working-with-microbial-abundances), which does explicitly show `using SparseArrays`, and for "dict" which got [me here](https://docs.ecojulia.org/Microbiome.jl/latest/samples_features/) - that spot does need `using Dictionaries`. There's also a missing link there.

Are you looking in the BiobakeryUtils tutorials as well?

**Comment by aguang** [comment]
The [stable version of the docs](https://docs.ecojulia.org/Microbiome.jl/stable/profiles/) does not have the `using SparseArrays` line.

**Comment by kescobo** [comment]
Ahh - good point. I'll add your suggestion from #111 and tag another version.

**Comment by kescobo** [comment]
This will be at least partly addressed by #115 - I added `MicrobiomeSample` constructors for julia base `Dict`s as well as `NamedTuple`s. The type still uses `Dictionaries.jl` under the hood, but a user shouldn't have to worry about adding that as a separate dependency in order to work with the type, I think.
