### ISSUE TITLE
vignette for data import

### ISSUE THREAD

**Issue by aguang** [EcoJulia/Microbiome.jl#112]
A vignette describing how to create `CommunityProfile` objects from imported CSVs would be helpful. The JOSS preprint says that it is trivial to go from `.csv` files to `CommunityProfile` and vice versa, but I did not find that to be the case. It wasn't extremely difficult, but I did have to convert my row names to a `Taxon` vector, my column names to a `MicrobiomeSample` vector, and my matrix to a `SparseMatrixCSC` object. If there is an easier way to do it then I would love to know and have that be in the documentation.

**Comment by kescobo** [comment]
You're right - that's the process :grimacing: ... I guess easy is relative here.

I wonder if a constructor like

```
communityprofile(t; featurecontructor)
```

Where `t` is a table and `featureconstructor` is a function that would be applied to the first column would be worth adding...
