### ISSUE TITLE
JuliaCon presentation

### ISSUE THREAD

**Issue by kescobo** [EcoJulia/Microbiome.jl#130]
## Things to do

- [x] Decide on most important things to cover
- [x] Decide what code we  should show?
- [x] Add tutorial / additional showcases?
- [x] Divide up responsibilities
- [ ] Deadlines?

## Dates

- JuliaCon: Juli 27-29
- Final pres due ~ Jul 20

**Comment by kescobo** [comment]
- Slides are looking good, I have some tweaks, which I'll comment on there. 
- Yes, OK to use the example files from the tutorial, but I would not make copies of them to put into the presentation directory. Just use relative paths.

**Comment by anikaluo** [comment]
@kescobo I incorporated your comments and asked followup questions where applicable for whenever you can take another look!
